# Generated by Django 5.0.1 on 2024-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=None, upload_to='task_images'),
        ),
    ]
