# Generated by Django 5.0.1 on 2024-02-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='task_images'),
        ),
    ]
